import assert from 'node:assert/strict'
import { normalizeHealthSample, healthStateText, healthFailureStatus, deterministicLocalAdvice, LOCAL_STRESS_REMINDER_THRESHOLD } from '../src/common/health-advice.js'

assert.deepEqual(normalizeHealthSample('heartRate', { timeStamp: 1, value: 48 }), { timeStamp: 1, value: 48 })
assert.deepEqual(normalizeHealthSample('heartRate', { timeStamp: 2, value: 182 }), { timeStamp: 2, value: 182 })
assert.deepEqual(normalizeHealthSample('spo2', { timeStamp: 3, value: 99 }), { timeStamp: 3, value: 99 })
assert.deepEqual(normalizeHealthSample('stress', { timeStamp: 4, value: 49 }), { timeStamp: 4, value: 49 })
assert.equal(normalizeHealthSample('unknown', { timeStamp: 1, value: 50 }), null)
assert.equal(normalizeHealthSample('heartRate', null), null)
assert.equal(normalizeHealthSample('heartRate', []), null)
assert.equal(normalizeHealthSample('heartRate', { value: 60 }), null)
assert.equal(normalizeHealthSample('heartRate', { timeStamp: '1', value: 60 }), null)
assert.equal(normalizeHealthSample('heartRate', { timeStamp: Infinity, value: 60 }), null)
assert.equal(normalizeHealthSample('heartRate', { timeStamp: 1, value: NaN }), null)
assert.equal(normalizeHealthSample('heartRate', { timeStamp: 1, value: 47 }), null)
assert.equal(normalizeHealthSample('heartRate', { timeStamp: 1, value: 183 }), null)
assert.equal(normalizeHealthSample('spo2', { timeStamp: 1, value: 89 }), null)
assert.equal(normalizeHealthSample('spo2', { timeStamp: 1, value: 99.5 }), null)
assert.equal(normalizeHealthSample('stress', { timeStamp: 1, value: 0 }), null)
assert.equal(healthStateText({ status: 'unsupported', code: 203 }), '当前设备暂不支持')
assert.equal(healthStateText({ status: 'invalid-sample' }), '暂无有效健康数据')
assert.equal(healthStateText({ status: 'read-error', reason: 'subscribe-error' }), '健康数据暂时读取失败')
assert.equal(healthStateText({ status: 'read-error', code: 204 }), '健康数据暂时读取失败')
assert.equal(healthStateText(null), '健康数据暂时读取失败')
assert.equal(healthFailureStatus(203), 'unsupported')
assert.equal(healthFailureStatus(204), 'read-error')
assert.equal(healthFailureStatus(undefined), 'read-error')

const foods = [{ id: 'rice', category: '主食' }, { id: 'greens', category: '蔬菜' }]
const meal = foodId => ({ items: [{ foodId }] })
const advice = values => deterministicLocalAdvice(Object.assign({ stress: null, intakeTargetDeltaKcal: 500, meals: [], foods }, values))
assert.equal(LOCAL_STRESS_REMINDER_THRESHOLD, 40)
assert.match(advice({ stress: 40, intakeTargetDeltaKcal: -1, meals: [] }), /呼吸一分钟/)
assert.match(advice({ stress: 39, intakeTargetDeltaKcal: -1, meals: [] }), /高于饮食参考线/)
assert.match(advice({ meals: [] }), /还没有记录餐食/)
assert.match(advice({ meals: [meal('rice')] }), /还没有蔬菜/)
assert.match(advice({ meals: [meal('greens')] }), /继续按实际份量记录/)
assert.match(advice({ meals: [meal('missing')] }), /还没有蔬菜/)

console.log('M4 健康样本与本地建议测试通过：形状、有限值、Mock 范围、三态文案与建议优先级均已覆盖。')
