import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = name => readFileSync(new URL('../src/pages/' + name + '/' + name + '.ux', import.meta.url), 'utf8')

const home = read('home')
assert.match(home, /今日已记录/)
assert.match(home, /每日饮食参考线 \{\{dailyTargetKcal\}\} kcal/)
assert.match(home, /按已记录餐食计算 · \{\{intakeProgress\}\}%/)
assert.match(home, /连续记录 \{\{streakDays\}\} 天/)
assert.match(home, /今天尚未记录/)
assert.match(home, /早餐\{\{breakfastState\}\} · 午餐\{\{lunchState\}\} · 晚餐\{\{dinnerState\}\}/)
assert.match(home, /系统健康数据/)
assert.match(home, /最近 7 天饮食记录/)
for (const removed of ['食衡三环', '食品种类', '手动补录运动', '估算净摄入', '剩余目标']) assert.equal(home.includes(removed), false)

const onboarding = read('onboarding')
assert.match(onboarding, /每日饮食参考线/)
assert.match(onboarding, /2000 kcal 是成人食品营养标签采用的一日能量参考值/)
assert.match(onboarding, /不是个人饮食处方，也不要求必须吃满/)
assert.match(onboarding, /实际需要会随年龄、性别、体型和活动量变化/)
assert.match(onboarding, /min="1200" max="4000" step="100"/)
assert.match(onboarding, /dailyTargetReferenceText/)
assert.doesNotMatch(onboarding, /体重（|weightValue|weightLabel|MET/)

const meal = read('meal')
assert.match(meal, /entryMode:'transcript'/)
assert.match(meal, /一句话记餐/)
assert.match(meal, /快捷选择/)
assert.match(meal, /识别这顿饭/)
assert.match(meal, /type="text" range="\{\{transcriptExamples\}\}"/)
assert.match(meal, /this\.transcriptExampleIndex=event\.newValue/)
assert.match(meal, /全部（60）/)
assert.match(meal, /当前显示 60 \/ 共 60 项/)
assert.match(meal, /minusDraft/)
assert.match(meal, /removeDraft/)
assert.match(meal, /clearDraft/)
assert.match(meal, /MEAL_TEMPLATE_NOTE/)
const transcriptEntryIndex = meal.indexOf('value="一句话记餐"')
assert.ok(transcriptEntryIndex >= 0 && transcriptEntryIndex < meal.indexOf('最近食品</text>'), '一句话入口必须排在快捷目录前')
assert.doesNotMatch(meal, /麦克风|录音中|识别中/)

const history = read('history')
assert.match(history, /最近 7 天饮食记录/)
assert.match(history, /有记录天数/)
assert.match(history, /有记录日平均 kcal/)
assert.match(history, /已记录 \{\{day\.mealCount\}\} 餐/)
assert.match(history, /仅根据已记录餐食统计，记录不完整时不代表实际全天摄入/)
for (const removed of ['食品种类', '手动补录', '估算净摄入']) assert.equal(history.includes(removed), false)

const manifest = JSON.parse(readFileSync(new URL('../src/manifest.json', import.meta.url), 'utf8'))
assert.equal(Object.prototype.hasOwnProperty.call(manifest.router.pages, 'pages/exercise'), false)
assert.equal(Object.keys(manifest.router.pages).length, 6)

console.log('食衡界面文案与主流程静态检查通过：参考线、单一摄入进度、连续记录和纯饮食七天摘要均符合要求。')
